### PR TITLE
Fix pre and post show tab and item hooks

### PR DESCRIPTION
**Pull request by trasher**
we're waiting for a single sring here, not an array; see https://github.com/glpi-project/glpi/blob/master/inc/plugin.class.php#L1132

### CODE REVIEW

**Comment by tomolimo** [comment]
Hello,
You cannot commit this, as it is done like this by designed!
Please, if you need to un-commit something: ask, before, to know why it has been done like it's done...
Thank you to revert your commit.
Regards,
Tomolimo

**Comment by trasher** [comment]
The commit is in a separate branch, no need to revert anything, it has not been merged.

The existing hooks does not work with current glpi master; one of GLPI or example plugin seems to be wrong here.

**Comment by trasher** [comment]
Ping?

**Comment by tomolimo** [comment]
Hello,
The fix I pushed yesterday was about a regression done here: 8c390effec3fbb6bec2a774c104258b28e5208f7
It has nothing to do with your own PR
regards,
Tomolimo

**Comment by trasher** [comment]
As I've said last month: "The existing hooks does not work with current glpi master; one of GLPI or example plugin seems to be wrong here." (see changes on setup.php). As far as I know, this does not work with 9.1 nor master actually.

**Comment by tomolimo** [comment]
I can't reproduce your problem :( it's working correctly on my dev system.
Could you give any error message, or clue to be able to reproduce?
I'm also going to try to reproduce on my test system.

**Comment by trasher** [comment]
We are using the "standard" case, because hooks are callde like this in core:
```
Plugin::doHook('pre_show_item', array('item' => $item, 'options' => &$options));
```
(second parameter is not an object)

So, in core, we reach the following code:
```
         if (isset($PLUGIN_HOOKS[$name]) && is_array($PLUGIN_HOOKS[$name])) {
            foreach ($PLUGIN_HOOKS[$name] as $plug => $function) {
               if (file_exists(GLPI_ROOT . "/plugins/$plug/hook.php")) {
                  include_once(GLPI_ROOT . "/plugins/$plug/hook.php");
               }
               if (is_callable($function)) {
                  call_user_func($function,$data);
               }
            }
         }
```

So, the `$function` has to be a simple string. In the actual hook config, you got:
```
$PLUGIN_HOOKS['pre_show_tab']['example'] = array( 'PluginExampleShowtabitem',  'pre_show_tab' );
```

`$function` value will be `array( 'PluginExampleShowtabitem',  'pre_show_tab' )`. The `is_callable` will return false, so no error, but hook won't work.

**Comment by tomolimo** [comment]
I don't agree with you, `is_callable` will return true, as it can be used with both syntaxes, see http://php.net/manual/en/function.is-callable.php 
And again, this example is running correctly on my dev system...

**Comment by trasher** [comment]
```
$ php -v
PHP 5.6.27 (cli) (built: Oct 14 2016 14:41:33) 
$ php -a
php > $a = ['PluginExampleShowtabitem', 'pre_show_tab'];
php > var_dump(is_callable($a));
bool(false)
```

**Comment by tomolimo** [comment]
:)
See the following screen copies using the example plugin as is (in yellow are the breakpoints in VS2012):

in setup.php:
image

and then in real execution in a ticket > processing tab:
pre_show_tab:
image

pre_show_item:
image


post_show_item:
image


and post_show_tab:
image


These hooks are working as explained!

Could it be an effect of PHP 7 ?

**Comment by tomolimo** [comment]
To be tested

```
<?php
class Foo {
  public function PublicMethod() {}
  private function PrivateMethod() {}
  public static function PublicStaticMethod() {}
  private static function PrivateStaticMethod() {}
}
 
$foo = new Foo();
 
$callbacks = array(
  array($foo, 'PublicMethod'),
  array($foo, 'PrivateMethod'),
  array($foo, 'PublicStaticMethod'),
  array($foo, 'PrivateStaticMethod'),
  array('Foo', 'PublicMethod'),
  array('Foo', 'PrivateMethod'),
  array('Foo', 'PublicStaticMethod'),
  array('Foo', 'PrivateStaticMethod'),
);
 
foreach ($callbacks as $callback) {
  var_dump($callback);
  var_dump(method_exists($callback[0], $callback[1])); // 0: object / class name, 1: method name
  var_dump(is_callable($callback));
  echo str_repeat('-', 40), "n";
}
```

**Comment by tomolimo** [comment]
Tested with php 7.0.11 and with php 5.6.24: results are identical

**Pull request closed without merging**
