### PR TITLE
Proposal : Transfer files with api

### PR DESCRIPTION
**Pull request by btry**
The itemtype PluginExampleDocument reuses the itemtype Document for file uploads, and provides a method for file downloads with range support.

### CODE REVIEW

**Comment by trasher** [comment]
How can this be tested? I can't find... :(

**Comment by btry** [comment]
You need cURL or Postman because this is exclusively for the new API. I'll provide examples of requests here, and I think I may add them in phpdoc or comments.

**Comment by trasher** [comment]
OK; :+1: to add some CURL examples on how to handle that in the phpdoc :)

**Comment by btry** [comment]
This PR has been forgotten. Update done, cutrl example provided (and tested for real)

**Review by cedric-anne — APPROVED** [review]

**Review by orthagh — APPROVED** [review]

**Pull request merged**
